### ISSUE TITLE
Error: Read depth

### ISSUE THREAD

**Issue by hcurley2** [Illumina/gvcfgenotyper#11] opened 2019-07-11 10:40 UTC
Hello, 

I am trying to use your tool on a rather large dataset. I have subdivided chromosomes further into 20-25million bp parts. 
Chr 22 = 4 parts. 

Parts1 and 2 have genotyped perfectly. 

Part 3 error:
ERROR: GVCFReader ::get_depth problem with depth buffer

Part 4 error: 
DepthBlock 21:38114251-38114251 does not contain region: 21:3811429-38114249
This can be caused by inconsistent genome references between GVCFs. 
ERROR: DepthBlock: bad coordinates. 

I am in the process of ensuring the same reference was used - but I don't think this is the problem. I am trying to genotype Chr22 and the error is about a region in Chr21? - This error is not observed when I genotype any of the other chromosomes either. 

Do you have any idea why these error messages would be occurring only upon trying to genotype these regions? 

Many Thanks.
Helen Curley

**Comment by olest** [comment] 2019-07-12 14:39
Hi Helen, this error message is confusing because the library (htslib) that gvcfgenotyper uses to parse VCF files starts counting at zero whereas Human start counting at one. So chr21 does mean chr22.

This error message could be caused by variants that extend past the end of parts into which you divided the chromosomes. For example, your chromosome part ends at N but one of the gVCF files has a variant that ends at position N+x. 

Another possibility is that the gVCF files does not contain depth info (DP) at each position. This is an assumption in gvcfgenotyper but it should hold true for the strelka variant caller.

You should take a look at your gVCF files in the region [3811429,38114251] using bcftools and see what is going on here. 

Feel free to follow up if this answer does not help.

**Comment by olest** [comment] 2020-01-02 14:16
Closing this now, please re-open this ticket if any questions remain.

**Closed as completed by olest** 2020-01-02 14:16 UTC
