### ISSUE TITLE
gvcfGenotyper taking too much time for MT chromosome

### ISSUE THREAD

**Issue by ajaarma** [Illumina/gvcfgenotyper#8] opened 2019-02-22 19:14 UTC
I am genotyping 760 vcf files splitted across all chromsomes chr1...22,X,Y and MT in the cluster. The vcf files were obtained using accredited Illumina pipeline. Run for all chromosome finished successfully approx 3-4 hours. But for chrMT, it is taking endless time. The log points out that it is stucked for one of the sample. However after deleting that sample from the input list it gets stucked at some other sample and this goes on. 

Example log : 
...
...
[Fri Feb 22 18:43:34 2019] [info] Opened Sample1.genome.vcf.gz 751/759
[Fri Feb 22 18:43:34 2019] [warning] WARNING: Sample1.genome.vcf.gz has no FORMAT/ADF tag
[Fri Feb 22 18:43:34 2019] [warning] WARNING: Sample1.genome.vcf.gz has no FORMAT/ADR tag
[Fri Feb 22 18:43:34 2019] [warning] WARNING: Sample1.genome.vcf.gz has

It gets stucked at the last line for more than 10+ hours.

Please help me regarding this.

**Comment by olest** [comment] 2019-02-26 10:49
I am sorry to hear that! 

I cannot reproduce this error on our side. Using 150 gVCF files from a recent run of the Illumina variant caller, I can merge MT in seconds.

One potential problem that comes to my mind is that gvcfgenotyper assumes diploidy. Recent versions of the Illumina variant caller should follow the diploid convention even for calls on MT but it is worth checking. 

Another option is the remove the comments from this line:

https://github.com/Illumina/gvcfgenotyper/blob/b95ae4af6be29b72357ab8a0b2a5c0daa74e2116/src/cpp/lib/GVCFMerger.cpp#L12

recompile, and run again. This will tell you where on MT gvcfgenotyper stalls.

If you find out where gvcfgenotyper stalls I can debug further and help to fix the issue.

**Comment by ajaarma** [comment] 2019-03-07 16:44
Hi,

As per your advice, I uncommented line 12, compiled again and re-ran the analysis. It got stuck again with following output on the screen:
MT:6:C:G

And the logs are:
[Thu Mar 7 16:29:25 2019] [info] Opened <path-to-dir>/SampleXYZ.genome.vcf.gz 755/759
 [Thu Mar 7 16:29:25 2019] [warning] WARNING: <path-to-dir>/SampleXYZ.genome.vcf.gz has no FORMAT/ADF tag
 [Thu Mar 7 16:29:25 2019] [warning] WARNING: <path-to-dir>/

**Comment by jaredo** [comment] 2019-03-08 00:46
What reference genome is this?

Could you post the full command line you used?

**Comment by ajaarma** [comment] 2019-03-08 12:08
The reference genome used is: GRCh37.74 and here is the exact command issued:  

<path-to-gvcf-binaries>/gvcfgenotyper-master/bin/gvcfgenotyper 
  -l <path-to-input-samples>/759_samples_final.txt 
  -Ob -o <path-to-output>/gvcfGT_tmp_chrMT.bcf 
  -f <path-to-ref>/Homo_sapiens.GRCh37.74.dna.fasta 
  -r MT 
  -L <path-to-log>gvcfGT_tmp_chrMT.log

**Comment by jaredo** [comment] 2019-03-08 19:54
hmmm okay. Illumina pipelines usually use hg19 which is slightly different to grch37

If you do:

```
bcftools norm -f /Homo_sapiens.GRCh37.74.dna.fasta Sample1.genome.vcf.gz  > /dev/null
```

does it run without error?

**Comment by ajaarma** [comment] 2019-03-08 20:10
Hi,

I tried this command: 
bcftools norm 
-r MT 
-f Homo_sapiens.GRCh37.74.dna.fasta Sample1.genome.vcf.gz
 -Ob -o OutSample1.bcf

It was successful and had following screen output:
Lines   total/split/realigned/skipped:  2687/0/1/0

Also I can access/view the OutSample1.bcf using bcftools.

**Comment by olest** [comment] 2019-03-11 15:27
So you're convinced that you're using that correct reference for your gvcf files? 

If yes, could you extract a mini-gvcf containing only MT for one of your samples and upload it somewhere (ftp?) where I could take a look at it? 

I have no other idea how we could debug this.

**Comment by olest** [comment] 2019-08-06 15:31
I'm closing this now, feel free to open another issue if there are any other questions.

**Closed as completed** 2019-08-09 08:06 UTC
Labels: question
